type: server

client_package_path: ../placeify_client
server_test_tools_path: test/integration/test_tools

modules:
  serverpod_auth_core:
    nickname: auth
  serverpod_auth_idp:
    nickname: auth_idp
