name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.4.8'
      SERVERPOD_PASSWORD_database: 'ajzc6u1uPyDjeg0SXp61RXK22hm7mqsJ'
      SERVERPOD_PASSWORD_redis: 'Ae3cNAo_yL9CdlS4MIJa_DycO050OwG6'
      SERVERPOD_PASSWORD_serviceSecret: 'placeify_test_service_secret'
      SERVERPOD_PASSWORD_emailSecretHashPepper: 'placeify_test_email_pepper'
      SERVERPOD_PASSWORD_jwtRefreshTokenHashPepper: 'placeify_test_refresh_pepper'
      SERVERPOD_PASSWORD_jwtHmacSha512PrivateKey: 'placeify_test_jwt_private_key'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: placeify_server
        run: docker compose up --quiet-pull --quiet-build --build -d

      - name: Install dependencies
        working-directory: placeify_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: placeify_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: placeify_server
        run: serverpod generate

      - name: Run tests
        working-directory: placeify_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: placeify_server
        run: docker compose down -v
